In [1]:
import selenium
import pandas as pd 
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
from selenium.webdriver.common.by import By
import time

In [2]:
driver=webdriver.Chrome(r"F:\flip robo\chromedriver.exe")

In [3]:
driver.get("http://www.naukri.com/")

In [4]:
designation=driver.find_element(By.CLASS_NAME,"suggestor-input")
designation.send_keys('Data Scientist')

In [5]:
search=driver.find_element(By.CLASS_NAME,"qsbSubmit")
search.click()

In [11]:
# using fliter selected location
location=driver.find_element(By.XPATH,"/html/body/div[1]/div[4]/div/section[1]/div[2]/div[5]/div[2]/div[3]/label/p/span[1]")
location.click()

In [12]:
# using fliter selected salary
salary=driver.find_element(By.XPATH,"/html/body/div[1]/div[4]/div/section[1]/div[2]/div[6]/div[2]/div[2]/label/p/span[1]")
salary.click()

In [13]:
job_title=[]
job_location=[]
company_name=[]
experience_required=[]

In [16]:
#scraping job title from the given page
title_tags=driver.find_elements(By.XPATH,'//a[@class="title fw500 ellipsis"]')
for i in title_tags[0:10]:
    title=i.text
    job_title.append(title)
    
#Scraping job location from the given page
location_tags=driver.find_elements(By.XPATH,'//li[@class="fleft grey-text br2 placeHolderLi location"]')
for i in location_tags[0:10]:
    location=i.text
    job_location.append(location)
    
    
#scraping company name from the given page
company_tags=driver.find_elements(By.XPATH,'//a[@class="subTitle ellipsis fleft"]')
for i in company_tags[0:10]:
    company=i.text
    company_name.append(company)
    
#scraping experience_required from the given page
experience_tags=driver.find_elements(By.XPATH,'//span[@class="ellipsis fleft fs12 lh16 "]')
for i in experience_tags[0:10]:
    experience=i.text
    experience_required.append(experience)

In [18]:
#creating dataframe
df=pd.DataFrame({'job_title':job_title,'job_location':job_location,'company_name':company_name,'experience_required':experience_required})
df

,job_title,job_location,company_name,experience_required
0,Data Scientist,8-10 Yrs,GlobalLogic,8-10 Yrs
1,DigitalBCG GAMMA Data Scientist,"3,00,000 - 4,50,000 PA.",Boston Consulting Group,"3,00,000 - 4,50,000 PA."
2,Data Scientist,"Noida, Nagpur, Bangalore/Bengaluru",Optum,"Noida, Nagpur, Bangalore/Bengaluru"
3,Data Scientist / Chat-bot Developer,2-5 Yrs,Big Seo Buzz,2-5 Yrs
4,Lead Data Scientist,Not disclosed,R Systems International,Not disclosed
5,Data Scientist - Predictive Analytics,"New Delhi, Bangalore/Bengaluru",Confidential,"New Delhi, Bangalore/Bengaluru"
6,Data Scientist For Healthcare Product team,2-7 Yrs,SECUREKLOUD TECHNOLOGIES,2-7 Yrs
7,Data Scientist - Engine Algorithm,Not disclosed,Primo Hiring,Not disclosed
8,Data Scientist,Gurgaon/Gurugram,Feedback Infra,Gurgaon/Gurugram
9,Data Scientist,3-7 Yrs,4i Odc,3-7 Yrs
10,Data Scientist,"Noida, Nagpur, Bangalore/Bengaluru",GlobalLogic,8-10 Yrs
11,DigitalBCG GAMMA Data Scientist,"New Delhi, Bangalore/Bengaluru",Boston Consulting Group,"3,00,000 - 4,50,000 PA."
12,Data Scientist,Gurgaon/Gurugram,Optum,"Noida, Nagpur, Bangalore/Bengaluru"
13,Data Scientist / Chat-bot Developer,"New Delhi, Bangalore/Bengaluru, Mumbai (All Ar...",Big Seo Buzz,2-5 Yrs
14,Lead Data Scientist,Noida(Sector-59 Noida)\n(WFH during Covid),R Systems International,Not disclosed
15,Data Scientist - Predictive Analytics,"Noida, Mumbai, Chandigarh, Hyderabad/Secundera...",Confidential,"New Delhi, Bangalore/Bengaluru"
16,Data Scientist For Healthcare Product team,"Delhi / NCR, Chennai, Bangalore/Bengaluru",SECUREKLOUD TECHNOLOGIES,2-7 Yrs
17,Data Scientist - Engine Algorithm,"Delhi / NCR, Kolkata, Mumbai, Hyderabad/Secund...",Primo Hiring,Not disclosed
18,Data Scientist,Gurgaon/Gurugram,Feedback Infra,Gurgaon/Gurugram
19,Data Scientist,Noida,4i Odc,3-7 Yrs